### ISSUE TITLE
Unable to generate

### ISSUE THREAD

**Issue by nemonemi** [kien-ht/cypress-image-diff-html-report#12]
I am trying this library, and regardless of what I do, it doesn't work.

I've tried running the command without any configuration, passing it inline or creating a configuration file with the required props, but nothing helps.
```ts
➜  cypress-image-diff-html-report generate -c reportJsonDir="./cypress-image-diff-html-report"

[cypress-image-diff-html-report]: Given reportJsonDir does not exist /home/develop/my-repo/cypress-image-diff-html-report. Make sure you specify a valid reportJsonDir or reportJsonFilePath
```

**Comment by kien-ht** [comment]
Hi @nemonemi , are you sure you have run the test and had the report json in place?

**Comment by nemonemi** [comment]
Hi @kien-ht, your quick response is much appreciated.

I am using this library through another [library](https://cypress.visual-image-diff.dev/getting-started/cypress-integration), and that is where I've experienced but I found a way how to
