### ISSUE TITLE
feature request: add sorting possibility to actual diff

### ISSUE THREAD

**Issue by MoritzMeinhardt** [kien-ht/cypress-image-diff-html-report#20]
Hi there, 

It would be helpful for us to be able to sort by the column actual to see what passed tests show the most diff in order to double check the failure treshold.

Thanks for the great package!

Best Moritz

**Comment by kien-ht** [comment]
This feature has been released, https://github.com/kien-ht/cypress-image-diff-html-report/commit/e1429d99073b2acd26002dd98a62fc64c6020a32
