### ISSUE TITLE
Add support for adding new baseline screenshots.

### ISSUE THREAD

**Issue by bpraznik** [kien-ht/cypress-image-diff-html-report#21]
Hi, 

love the package but hit a small snag. I'm using the `FAIL_ON_MISSING_BASELINE` flag from `cypress-image-diff`, so that new tests fail and people are forced to add the new baseline manually. I would love to do this via the report but it seems that this is not supported. From a quick check the issue is in the following code, because `baselinePath` is required. 
https://github.com/kien-ht/cypress-image-diff-html-report/blob/d68f136373a8851cac191341b50aee0c9c2fd0d3/src/local-server/controller.ts#L65

My suggestion would be a check for `baselinePath` and if empty to construct it based on the `comparisonPath`.

**Comment by bpraznik** [comment]
Created a PR https://github.com/kien-ht/cypress-image-diff-html-report/pull/22. Not too happy with hard-coding `/comparison/` and `/baseline/` but since we don't have base paths in the report json this was my try. Another option would be to get the base path for baseline from other tests, tho that seems more hacky.

**Comment by kien-ht** [comment]
Hi @bpraznik, thank you for your prompt pull request. I'll take a look around this weekend.
